# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE are ignored when building from the
# command line. Check Gradle settings in the IDE.

# For more details on how to configure your build environment visit
# http://www.gradle.org/configure-gradle

# Specifies the JVM arguments used for the daemon process.
# The setting is particularly useful for headless machines. See also
# http://gradle.org/docs/current/userguide/build_environment.html
# Specifying a JVM argument requires a matching system property name with "org.gradle" prefix. All
# other JVM args should be in JAVA_OPTS environment variable (See also
# http://gradle.org/docs/current/userguide/build_environment.html)
org.gradle.jvmargs=-Xmx2048m
# When configured, Gradle will run in incubating parallel mode.
# This option should only be used with decoupled projects. More details, visit
# http://www.gradle.org/docs/current/userguide/multi_project_builds/#sec:decoupled_projects
# org.gradle.parallel=true

# AndroidX package structure to make it easier to discover and migrate existing, old-style packages
android.useAndroidX=true

# Enables namespacing of each library's R class so that its R class includes only the
# resources declared in the library itself and does not include any resources from library
# dependencies,
android.nonTransitiveRClass=true

# Build features
kotlin.jvm.target=11
